<script setup lang="ts">
import{computed,ref,onMounted,onUnmounted}from'vue';import RBush from'rbush';import{ZoomIn,ZoomOut,Maximize,MousePointer2,Type,Frame,Link2,Grid2X2,AlignLeft,Trash2,Globe2}from'lucide-vue-next';import NodeCard from'./NodeCard.vue';import{useWorkspace}from'../stores/workspace';import{backend}from'../services/backend';import{history}from'../canvas/history';import type{CanvasNode}from'../types';
const ws=useWorkspace(),root=ref<HTMLElement>(),camera=ref({x:0,y:0,zoom:1}),space=ref(false),selectBox=ref<{x:number,y:number,w:number,h:number}|null>(null),edgeMode=ref(false),edgeSource=ref(''),selectedEdge=ref('');let drag:any=null,persistTimer:any;
const tree=computed(()=>{const t=new RBush<any>();t.load(ws.nodes.map(n=>({minX:n.x,minY:n.y,maxX:n.x+n.width,maxY:n.y+n.height,id:n.id})));return t});
const viewport=computed(()=>{const el=root.value,w=el?.clientWidth||2000,h=el?.clientHeight||1200,z=camera.value.zoom,p=500/z;return{minX:-camera.value.x/z-p,minY:-camera.value.y/z-p,maxX:(w-camera.value.x)/z+p,maxY:(h-camera.value.y)/z+p}});
const visible=computed(()=>{const ids=new Set(tree.value.search(viewport.value).map(x=>x.id));return ws.nodes.filter(n=>ids.has(n.id))});const lod=computed(()=>camera.value.zoom<.1?0:camera.value.zoom<.3?1:2);
const selectedNodes=computed(()=>ws.nodes.filter(n=>ws.selected.has(n.id)));const miniBounds=computed(()=>{if(!ws.nodes.length)return{x:0,y:0,w:1,h:1};const xs=ws.nodes.map(n=>n.x),ys=ws.nodes.map(n=>n.y),xe=ws.nodes.map(n=>n.x+n.width),ye=ws.nodes.map(n=>n.y+n.height);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xe)-Math.min(...xs)||1,h:Math.max(...ye)-Math.min(...ys)||1}});
function world(e:{clientX:number;clientY:number}){const r=root.value!.getBoundingClientRect();return{x:(e.clientX-r.left-camera.value.x)/camera.value.zoom,y:(e.clientY-r.top-camera.value.y)/camera.value.zoom}}
function wheel(e:WheelEvent){if(e.ctrlKey){e.preventDefault();const old=camera.value.zoom,n=Math.min(8,Math.max(.05,old*Math.exp(-e.deltaY*.002))),r=root.value!.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;camera.value={x:px-(px-camera.value.x)*n/old,y:py-(py-camera.value.y)*n/old,zoom:n}}else{camera.value.x-=e.deltaX;camera.value.y-=e.deltaY}}
function backgroundDown(e:PointerEvent){selectedEdge.value='';if(e.button===1||space.value){drag={kind:'pan',sx:e.clientX,sy:e.clientY,cx:camera.value.x,cy:camera.value.y};return}const p=world(e);if(!e.shiftKey)ws.selected.clear();selectBox.value={x:p.x,y:p.y,w:0,h:0};drag={kind:'box',start:p}}
function nodeDown(e:PointerEvent,n:CanvasNode){selectedEdge.value='';if(edgeMode.value){if(!edgeSource.value)edgeSource.value=n.id;else if(edgeSource.value!==n.id){ws.data!.edges.push({id:crypto.randomUUID(),canvas_id:n.canvas_id,source_node_id:edgeSource.value,target_node_id:n.id,type:'curve',label:'',style_json:'{}',created_at:Date.now(),updated_at:Date.now()});backend.saveEdges(ws.data!.edges);edgeSource.value='';edgeMode.value=false}return}if(!e.shiftKey&&!ws.selected.has(n.id))ws.selected=new Set([n.id]);else if(e.shiftKey){const s=new Set(ws.selected);s.has(n.id)?s.delete(n.id):s.add(n.id);ws.selected=s}const p=world(e),before=selectedNodes.value.map(x=>({...x}));drag={kind:'nodes',start:p,before}}
function resizeDown(e:PointerEvent,n:CanvasNode){drag={kind:'resize',node:n,start:world(e),w:n.width,h:n.height}}
function fitImage(n:CanvasNode,naturalWidth:number,naturalHeight:number){const fitted=Math.round(n.width*naturalHeight/naturalWidth+32);if(Math.abs(n.height-fitted)>2){n.height=fitted;n.updated_at=Date.now();ws.saveNodes([n])}}
function pointerMove(e:PointerEvent){if(!drag)return;if(drag.kind==='pan'){camera.value.x=drag.cx+e.clientX-drag.sx;camera.value.y=drag.cy+e.clientY-drag.sy}else if(drag.kind==='box'){const p=world(e),s=drag.start;selectBox.value={x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y)};const b=selectBox.value;ws.selected=new Set(tree.value.search({minX:b.x,minY:b.y,maxX:b.x+b.w,maxY:b.y+b.h}).map(x=>x.id))}else if(drag.kind==='nodes'){const p=world(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y;drag.before.forEach((b:CanvasNode)=>{const n=ws.nodes.find(x=>x.id===b.id)!;n.x=b.x+dx;n.y=b.y+dy;n.updated_at=Date.now()});debounceSave()}else if(drag.kind==='resize'){const p=world(e);drag.node.width=Math.max(80,drag.w+p.x-drag.start.x);drag.node.height=Math.max(50,drag.h+p.y-drag.start.y);debounceSave()}}
function pointerUp(){if(drag?.kind==='nodes'||drag?.kind==='resize')ws.saveNodes(selectedNodes.value);drag=null;selectBox.value=null}
function debounceSave(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>ws.saveNodes(selectedNodes.value),400)}
async function dbl(e:MouseEvent){const p=world(e);const n=await ws.createNode({x:p.x,y:p.y,type:'text',title:'',content_json:JSON.stringify({html:'开始输入…'})});if(n)ws.selected=new Set([n.id])}
async function addText(){const c=world({clientX:(root.value?.clientWidth||0)/2,clientY:(root.value?.clientHeight||0)/2});const n=await ws.createNode({x:c.x-150,y:c.y-100,width:300,height:200,type:'text',title:'文字笔记',content_json:JSON.stringify({html:'开始输入…'})});if(n)ws.selected=new Set([n.id])}
function zoomToAll(){if(!root.value||!ws.nodes.length)return;const b=miniBounds.value,p=100;const z=Math.min(2,Math.max(.05,Math.min((root.value.clientWidth-p*2)/b.w,(root.value.clientHeight-p*2)/b.h)));camera.value={zoom:z,x:(root.value.clientWidth-b.w*z)/2-b.x*z,y:(root.value.clientHeight-b.h*z)/2-b.y*z}}
function zoomSelection(){if(!selectedNodes.value.length)return;const old=ws.nodes,chosen=selectedNodes.value;(ws as any).nodes=chosen;zoomToAll();(ws as any).nodes=old}
async function addFrame(){const c=world({clientX:(root.value?.clientWidth||0)/2,clientY:(root.value?.clientHeight||0)/2});await ws.createNode({type:'frame',x:c.x-300,y:c.y-220,width:600,height:440,title:'新区域',z_index:0,content_json:'{}',style_json:JSON.stringify({background:'rgba(109,94,252,.06)'})})}
async function addLink(){let url=prompt('输入网页链接','https://');if(!url)return;url=url.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;try{const parsed=new URL(url),c=world({clientX:(root.value?.clientWidth||0)/2,clientY:(root.value?.clientHeight||0)/2});const n=await ws.createNode({type:'link',x:c.x-160,y:c.y-95,width:320,height:190,title:parsed.hostname.replace(/^www\./,''),content_json:JSON.stringify({url,domain:parsed.hostname}),style_json:'{}'});if(n)ws.selected=new Set([n.id])}catch{alert('请输入有效的网址')}}
async function group(){if(selectedNodes.value.length<2||!ws.data)return;ws.data.groups.push({id:crypto.randomUUID(),canvas_id:ws.activeCanvasId,name:'组合',node_ids:selectedNodes.value.map(n=>n.id)});await backend.saveGroups(ws.data.groups)}
function alignLeft(){if(selectedNodes.value.length<2)return;const x=Math.min(...selectedNodes.value.map(n=>n.x));selectedNodes.value.forEach(n=>n.x=x);ws.saveNodes(selectedNodes.value)}
const edgePaths=computed(()=>ws.edges.map(e=>{const a=ws.nodes.find(n=>n.id===e.source_node_id),b=ws.nodes.find(n=>n.id===e.target_node_id);if(!a||!b)return null;const x1=a.x+a.width/2,y1=a.y+a.height/2,x2=b.x+b.width/2,y2=b.y+b.height/2;return{...e,d:`M${x1},${y1} C${(x1+x2)/2},${y1} ${(x1+x2)/2},${y2} ${x2},${y2}`}}).filter(Boolean));
async function deleteSelection(){if(selectedEdge.value&&ws.data){const id=selectedEdge.value;ws.data.edges=ws.data.edges.filter(e=>e.id!==id);selectedEdge.value='';await backend.deleteEdges([id])}else await ws.trashSelected()}
function key(e:KeyboardEvent){space.value=e.code==='Space'||space.value;if((e.target as HTMLElement).isContentEditable||['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName))return;if(e.key==='Delete')deleteSelection();if(e.ctrlKey&&e.key==='a'){e.preventDefault();ws.selected=new Set(ws.nodes.map(n=>n.id))}if(e.ctrlKey&&e.key==='g'){e.preventDefault();group()}if(e.ctrlKey&&e.key==='0'){e.preventDefault();camera.value.zoom=1}if(e.ctrlKey&&e.key==='d'){e.preventDefault();selectedNodes.value.forEach(n=>ws.createNode({...n,id:crypto.randomUUID(),x:n.x+24,y:n.y+24}))}if(e.ctrlKey&&e.key==='z'){e.preventDefault();e.shiftKey?history.redo():history.undo()}}
function keyup(e:KeyboardEvent){if(e.code==='Space')space.value=false}onMounted(()=>{window.addEventListener('keydown',key);window.addEventListener('keyup',keyup)});onUnmounted(()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',keyup)});
</script>
<template><section ref="root" class="canvas" :class="{panning:space,edgeMode}" @wheel="wheel" @pointerdown="backgroundDown" @pointermove="pointerMove" @pointerup="pointerUp" @pointercancel="pointerUp" @dblclick.self="dbl">
 <div class="world" :style="{transform:`translate(${camera.x}px,${camera.y}px) scale(${camera.zoom})`}"><svg class="edges"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8z"/></marker></defs><g v-for="e in edgePaths" :key="e!.id" class="edge-group" :class="{selected:selectedEdge===e!.id}" @pointerdown.stop="selectedEdge=e!.id;ws.selected.clear()"><path class="edge-hit" :d="e!.d"/><path class="edge-visible" :d="e!.d" marker-end="url(#arrow)"/></g></svg><NodeCard v-for="n in visible" :key="n.id" :node="n" :asset="ws.assets.find(a=>a.id===n.asset_id)" :selected="ws.selected.has(n.id)" :zoom="camera.zoom" :lod="lod" @down="nodeDown($event,n)" @resize="resizeDown($event,n)" @image-loaded="(w,h)=>fitImage(n,w,h)" @edit="n.content_json=JSON.stringify({html:$event});ws.saveNodes([n])"/><div v-if="selectBox" class="select-box" :style="{left:selectBox.x+'px',top:selectBox.y+'px',width:selectBox.w+'px',height:selectBox.h+'px'}"/></div>
 <nav class="canvas-tools"><button title="选择"><MousePointer2/></button><button title="创建文字卡片" @click.stop="addText"><Type/></button><button title="创建链接卡片" @click.stop="addLink"><Globe2/></button><button title="Frame" @click.stop="addFrame"><Frame/></button><button title="连线" :class="{active:edgeMode}" @click.stop="edgeMode=!edgeMode"><Link2/></button><button title="组合" @click.stop="group"><Grid2X2/></button><button title="左对齐" @click.stop="alignLeft"><AlignLeft/></button><button title="删除" @click.stop="deleteSelection"><Trash2/></button></nav>
 <div class="zoom-controls"><button @click="camera.zoom=Math.max(.05,camera.zoom/1.2)"><ZoomOut/></button><button @click="camera.zoom=1">{{Math.round(camera.zoom*100)}}%</button><button @click="camera.zoom=Math.min(8,camera.zoom*1.2)"><ZoomIn/></button><button title="显示全部" @click="zoomToAll"><Maximize/></button></div>
 <div class="minimap" @click="zoomToAll"><div v-for="n in ws.nodes" :key="n.id" :class="n.type" :style="{left:(n.x-miniBounds.x)/miniBounds.w*100+'%',top:(n.y-miniBounds.y)/miniBounds.h*100+'%',width:Math.max(2,n.width/miniBounds.w*100)+'%',height:Math.max(2,n.height/miniBounds.h*100)+'%'}"/></div>
 <div v-if="edgeMode" class="hint">{{edgeSource?'请选择目标节点':'请选择起始节点'}}</div>
</section></template>
