<script setup lang="ts">import{computed,ref,nextTick}from'vue';import MarkdownIt from'markdown-it';import hljs from'highlight.js';import{File,Link2,Play,Music,Lock,ChevronDown,X,ZoomIn,FileText,Code2,BookOpen}from'lucide-vue-next';import{backend}from'../services/backend';import type{Asset,CanvasNode}from'../types';const p=defineProps<{node:CanvasNode;asset?:Asset;selected:boolean;zoom:number;lod:number}>();const emit=defineEmits<{down:[PointerEvent],resize:[PointerEvent],edit:[string],imageLoaded:[number,number],contextmenu:[MouseEvent]}>();const editing=ref(false),videoActive=ref(false),imagePreview=ref(false),documentPreview=ref(false),textPreview=ref(false),editor=ref<HTMLElement>(),draftTitle=ref('');const content=computed(()=>{try{return JSON.parse(p.node.content_json)}catch{return{}}});const mediaUrl=computed(()=>p.asset?backend.assetUrl(p.asset):content.value.url);const mdUtils=new MarkdownIt();const markdown=new MarkdownIt({html:false,linkify:true,breaks:true,highlight:(str:string,lang:string):string=>{try{return hljs.highlight(str,{language:lang}).value}catch{return mdUtils.utils.escapeHtml(str)}}});const renderedMarkdown=computed(()=>markdown.render(content.value.text||''));const highlightedCode=computed(()=>{const text=content.value.text||'';try{return hljs.highlight(text,{language:content.value.language||'plaintext'}).value}catch{return mdUtils.utils.escapeHtml(text)}});const style=computed(()=>{try{return JSON.parse(p.node.style_json)}catch{return{}}});function done(e:Event){editing.value=false;emit('edit',(e.target as HTMLElement).innerHTML)}async function openText(){draftTitle.value=p.node.title;textPreview.value=true;await nextTick();editor.value?.focus()}function saveText(){if(editor.value)emit('edit',editor.value.innerHTML);p.node.title=draftTitle.value;textPreview.value=false}function imageLoaded(e:Event){const img=e.target as HTMLImageElement;if(img.naturalWidth&&img.naturalHeight)emit('imageLoaded',img.naturalWidth,img.naturalHeight)}</script>
<template><article class="node" :class="[node.type,{selected,frame:node.type==='frame',collapsed:content.collapsed}]" :style="{transform:`translate(${node.x}px,${node.y}px) rotate(${node.rotation}deg)`,width:node.width+'px',height:node.height+'px',zIndex:node.z_index,background:style.background,color:style.color,opacity:style.opacity,borderRadius:(style.radius??10)+'px'}" @contextmenu.prevent.stop="emit('contextmenu',$event)" @pointerdown.stop="emit('down',$event)">
 <template v-if="lod===0"><div class="lod-block"/></template>
 <template v-else-if="node.type==='frame'"><header>{{node.title||'Frame'}}<Lock v-if="content.locked"/><ChevronDown v-if="content.collapsed"/></header></template>
 <template v-else-if="node.type==='text'"><div class="text-node-head"><span>{{node.title||'文字笔记'}}</span><button title="放大编辑" @click.stop="openText"><ZoomIn/></button></div><div class="text-content" @dblclick.stop="openText" v-html="content.html||node.title||'双击放大编辑文字'"/></template>
 <template v-else-if="node.type==='image'"><button v-if="mediaUrl" class="node-image-button" title="双击放大预览" @dblclick.stop="imagePreview=true"><img :src="mediaUrl" draggable="false" @load="imageLoaded"><ZoomIn/></button><div v-else class="placeholder">图片</div><footer :title="node.title">{{node.title}}</footer></template>
 <template v-else-if="node.type==='video'"><video v-if="videoActive&&mediaUrl" :src="mediaUrl" controls autoplay preload="metadata" @pointerdown.stop @dblclick.stop/><button v-else class="media-cover" @click.stop="videoActive=true"><img v-if="content.thumbnail" :src="content.thumbnail"><Play/><span>点击播放</span></button><footer>{{node.title}}<span>{{content.duration||''}}</span></footer></template>
 <template v-else-if="node.type==='audio'"><div class="audio-title"><Music/><b>{{node.title}}</b></div><div class="node-waveform" aria-label="音频波形"><i v-for="n in 38" :key="n" :style="{height:(7+(n*17+n*n*3)%38)+'px'}"/></div><audio v-if="mediaUrl&&lod>1" :src="mediaUrl" controls preload="metadata" @pointerdown.stop @dblclick.stop/></template>
 <template v-else-if="node.type==='pdf'"><button class="document-cover pdf-cover" @click.stop="documentPreview=true"><FileText/><b>{{node.title}}</b><span><BookOpen/>内置阅读</span></button></template>
 <template v-else-if="node.type==='markdown'"><div class="document-head"><FileText/>{{node.title}}<button title="放大预览" @click.stop="documentPreview=true"><ZoomIn/></button></div><div class="markdown-body" @dblclick.stop="documentPreview=true" v-html="renderedMarkdown"/></template>
 <template v-else-if="node.type==='code'"><div class="document-head"><Code2/>{{node.title}}<em>{{content.language}}</em><button title="放大预览" @click.stop="documentPreview=true"><ZoomIn/></button></div><pre class="code-body" @dblclick.stop="documentPreview=true"><code v-html="highlightedCode"/></pre></template>
 <template v-else-if="node.type==='link'"><div class="link-preview" :title="'双击打开 '+content.url" @dblclick.stop="content.url&&backend.openUrl(content.url)"><img v-if="content.image" :src="content.image"><span class="link-icon"><Link2/></span><b>{{node.title||content.url}}</b><p>{{content.description||content.url}}</p><small>{{content.domain||content.url}}</small></div></template>
 <template v-else><div class="node-file-body" title="双击使用系统默认程序打开" @dblclick.stop="asset&&backend.openAsset(asset.id)"><div class="file-icon"><File/></div><b>{{node.title}}</b><p>{{asset?.extension?.toUpperCase()||'FILE'}} · {{asset?Math.ceil(asset.size/1024)+' KB':''}}</p><small>双击打开</small></div></template>
 <i v-if="selected" class="resize" @pointerdown.stop="emit('resize',$event)"/></article><Teleport to="body"><div v-if="textPreview" class="text-editor-overlay" @pointerdown.self="textPreview=false"><section><header><input v-model="draftTitle" placeholder="笔记标题"><div><button @click="textPreview=false">取消</button><button class="primary" @click="saveText">完成</button></div></header><div ref="editor" class="expanded-text-editor" contenteditable="true" v-html="content.html||''"/></section></div><div v-if="imagePreview" class="media-lightbox" @click.self="imagePreview=false"><header><b>{{node.title}}</b><button @click="imagePreview=false"><X/></button></header><img :src="mediaUrl" :alt="node.title"></div><div v-if="documentPreview" class="document-reader" :class="'reader-'+node.type"><header><b>{{node.title}}</b><span v-if="node.type==='code'">{{content.language?.toUpperCase()}}</span><button @click="documentPreview=false"><X/></button></header><iframe v-if="node.type==='pdf'" :src="mediaUrl" title="PDF 阅读器"/><article v-else-if="node.type==='markdown'" class="markdown-reader" v-html="renderedMarkdown"/><pre v-else class="code-reader"><code v-html="highlightedCode"/></pre></div></Teleport></template>
