use rusqlite::Connection;use std::{fs,path::Path};use crate::models::*;
pub const SCHEMA:&str=r#"
PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS canvases(id TEXT PRIMARY KEY,name TEXT NOT NULL,camera_x REAL NOT NULL DEFAULT 0,camera_y REAL NOT NULL DEFAULT 0,zoom REAL NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER);
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY,type TEXT NOT NULL,original_name TEXT NOT NULL,storage_name TEXT NOT NULL,extension TEXT NOT NULL,mime_type TEXT NOT NULL,size INTEGER NOT NULL,hash TEXT NOT NULL UNIQUE,width INTEGER,height INTEGER,duration REAL,thumbnail_path TEXT,extracted_text TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER);
CREATE TABLE IF NOT EXISTS nodes(id TEXT PRIMARY KEY,canvas_id TEXT NOT NULL,asset_id TEXT,type TEXT NOT NULL,x REAL NOT NULL,y REAL NOT NULL,width REAL NOT NULL,height REAL NOT NULL,rotation REAL NOT NULL,z_index INTEGER NOT NULL,title TEXT NOT NULL,content_json TEXT NOT NULL,style_json TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER,FOREIGN KEY(canvas_id) REFERENCES canvases(id));
CREATE TABLE IF NOT EXISTS edges(id TEXT PRIMARY KEY,canvas_id TEXT NOT NULL,source_node_id TEXT NOT NULL,target_node_id TEXT NOT NULL,type TEXT NOT NULL,label TEXT NOT NULL,style_json TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS groups(id TEXT PRIMARY KEY,canvas_id TEXT NOT NULL,name TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS group_nodes(group_id TEXT NOT NULL,node_id TEXT NOT NULL,PRIMARY KEY(group_id,node_id));
CREATE TABLE IF NOT EXISTS tags(id TEXT PRIMARY KEY,name TEXT NOT NULL,color TEXT NOT NULL);CREATE TABLE IF NOT EXISTS node_tags(node_id TEXT NOT NULL,tag_id TEXT NOT NULL,PRIMARY KEY(node_id,tag_id));CREATE INDEX IF NOT EXISTS idx_nodes_canvas ON nodes(canvas_id);CREATE INDEX IF NOT EXISTS idx_nodes_position ON nodes(canvas_id,x,y);CREATE INDEX IF NOT EXISTS idx_nodes_title ON nodes(title);"#;
fn migrate(c:&Connection){let _=c.execute("ALTER TABLE assets ADD COLUMN extracted_text TEXT NOT NULL DEFAULT ''",[]);}
pub fn init(path:&Path,name:&str)->Result<Connection,String>{fs::create_dir_all(path).map_err(|e|e.to_string())?;for d in["assets/images","assets/videos","assets/audios","assets/files","thumbnails/256","thumbnails/512","thumbnails/1024","cache/import","recovery","trash"]{fs::create_dir_all(path.join(d)).map_err(|e|e.to_string())?}let c=Connection::open(path.join("workspace.db")).map_err(|e|e.to_string())?;c.execute_batch(SCHEMA).map_err(|e|e.to_string())?;migrate(&c);c.execute("INSERT OR REPLACE INTO meta(key,value)VALUES('name',?1)",[name]).map_err(|e|e.to_string())?;Ok(c)}
pub fn open(path:&Path)->Result<Connection,String>{let c=Connection::open(path.join("workspace.db")).map_err(|e|e.to_string())?;c.execute_batch(SCHEMA).map_err(|e|e.to_string())?;migrate(&c);Ok(c)}
fn rows<T,F>(c:&Connection,sql:&str,mut f:F)->Result<Vec<T>,String>where F:FnMut(&rusqlite::Row)->rusqlite::Result<T>{let mut s=c.prepare(sql).map_err(|e|e.to_string())?;let values=s.query_map([],|r|f(r)).map_err(|e|e.to_string())?.filter_map(Result::ok).collect();Ok(values)}
pub fn load(c:&Connection,path:&Path)->Result<WorkspaceData,String>{let name:String=c.query_row("SELECT value FROM meta WHERE key='name'",[],|r|r.get(0)).unwrap_or_else(|_|path.file_name().unwrap_or_default().to_string_lossy().into());let canvases=rows(c,"SELECT id,name,camera_x,camera_y,zoom,created_at,updated_at,deleted_at FROM canvases",|r|Ok(Canvas{id:r.get(0)?,name:r.get(1)?,camera_x:r.get(2)?,camera_y:r.get(3)?,zoom:r.get(4)?,created_at:r.get(5)?,updated_at:r.get(6)?,deleted_at:r.get(7)?}))?;let nodes=rows(c,"SELECT id,canvas_id,asset_id,type,x,y,width,height,rotation,z_index,title,content_json,style_json,created_at,updated_at,deleted_at FROM nodes",|r|Ok(Node{id:r.get(0)?,canvas_id:r.get(1)?,asset_id:r.get(2)?,kind:r.get(3)?,x:r.get(4)?,y:r.get(5)?,width:r.get(6)?,height:r.get(7)?,rotation:r.get(8)?,z_index:r.get(9)?,title:r.get(10)?,content_json:r.get(11)?,style_json:r.get(12)?,created_at:r.get(13)?,updated_at:r.get(14)?,deleted_at:r.get(15)?}))?;let assets=rows(c,"SELECT a.id,a.type,a.original_name,a.storage_name,a.extension,a.mime_type,a.size,a.hash,a.width,a.height,a.duration,a.thumbnail_path,a.created_at,a.updated_at,a.deleted_at,(SELECT COUNT(*) FROM nodes n WHERE n.asset_id=a.id AND n.deleted_at IS NULL) FROM assets a",|r|Ok(Asset{id:r.get(0)?,kind:r.get(1)?,original_name:r.get(2)?,storage_name:path.join(r.get::<_,String>(3)?).to_string_lossy().into(),extension:r.get(4)?,mime_type:r.get(5)?,size:r.get(6)?,hash:r.get(7)?,width:r.get(8)?,height:r.get(9)?,duration:r.get(10)?,thumbnail_path:r.get(11)?,created_at:r.get(12)?,updated_at:r.get(13)?,deleted_at:r.get(14)?,usage_count:r.get(15)?}))?;let edges=rows(c,"SELECT id,canvas_id,source_node_id,target_node_id,type,label,style_json,created_at,updated_at FROM edges",|r|Ok(Edge{id:r.get(0)?,canvas_id:r.get(1)?,source_node_id:r.get(2)?,target_node_id:r.get(3)?,kind:r.get(4)?,label:r.get(5)?,style_json:r.get(6)?,created_at:r.get(7)?,updated_at:r.get(8)?}))?;let groups=rows(c,"SELECT id,canvas_id,name FROM groups",|r|{let id:String=r.get(0)?;let mut s=c.prepare("SELECT node_id FROM group_nodes WHERE group_id=?1")?;let ids=s.query_map([&id],|x|x.get(0))?.filter_map(Result::ok).collect();Ok(Group{id,canvas_id:r.get(1)?,name:r.get(2)?,node_ids:ids})})?;Ok(WorkspaceData{workspace:WorkspaceInfo{path:path.to_string_lossy().into(),name,last_opened:None},canvases,nodes,assets,edges,groups,recovery_needed:path.join("recovery/dirty").exists()})}
