mod db;mod models;use models::*;use rusqlite::{params,Connection};use sha2::{Digest,Sha256};use std::{fs,io::Read,path::{Path,PathBuf},sync::Mutex};use tauri::State;use uuid::Uuid;
struct AppState(Mutex<Option<PathBuf>>);fn now()->i64{chrono::Utc::now().timestamp_millis()}fn root(s:&State<AppState>)->Result<PathBuf,String>{s.0.lock().map_err(|e|e.to_string())?.clone().ok_or("尚未打开工作区".into())}fn conn(s:&State<AppState>)->Result<Connection,String>{db::open(&root(s)?)}
#[tauri::command]fn create_workspace(path:String,name:String,state:State<AppState>)->Result<WorkspaceData,String>{let root=PathBuf::from(path);let c=db::init(&root,&name)?;if c.query_row("SELECT COUNT(*) FROM canvases",[],|r|r.get::<_,i64>(0)).unwrap_or(0)==0{let t=now();c.execute("INSERT INTO canvases(id,name,created_at,updated_at)VALUES(?1,'主页',?2,?2)",params![Uuid::new_v4().to_string(),t]).map_err(|e|e.to_string())?;}fs::write(root.join("recovery/dirty"),b"open").map_err(|e|e.to_string())?;*state.0.lock().unwrap()=Some(root.clone());db::load(&c,&root)}
#[tauri::command]fn open_workspace(path:String,state:State<AppState>)->Result<WorkspaceData,String>{let root=PathBuf::from(path);if!root.join("workspace.db").exists(){return Err("所选目录不是有效的 Infinite Canvas 工作区".into())}let c=db::open(&root)?;index_existing(&root,&c);let data=db::load(&c,&root)?;fs::write(root.join("recovery/dirty"),b"open").map_err(|e|e.to_string())?;*state.0.lock().unwrap()=Some(root);Ok(data)}
#[tauri::command]fn close_workspace(state:State<AppState>)->Result<(),String>{mark_clean_shutdown(state)}
#[tauri::command]fn mark_clean_shutdown(state:State<AppState>)->Result<(),String>{if let Ok(r)=root(&state){let p=r.join("recovery/dirty");if p.exists(){fs::remove_file(p).map_err(|e|e.to_string())?}}Ok(())}
#[tauri::command]fn create_canvas(name:String,state:State<AppState>)->Result<Canvas,String>{let c=conn(&state)?;let t=now();let row=Canvas{id:Uuid::new_v4().to_string(),name,camera_x:0.,camera_y:0.,zoom:1.,created_at:t,updated_at:t,deleted_at:None};c.execute("INSERT INTO canvases(id,name,camera_x,camera_y,zoom,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?7)",params![row.id,row.name,row.camera_x,row.camera_y,row.zoom,row.created_at,row.updated_at]).map_err(|e|e.to_string())?;Ok(row)}
#[tauri::command]fn update_canvas(canvas:Canvas,state:State<AppState>)->Result<(),String>{conn(&state)?.execute("UPDATE canvases SET name=?2,camera_x=?3,camera_y=?4,zoom=?5,updated_at=?6 WHERE id=?1",params![canvas.id,canvas.name,canvas.camera_x,canvas.camera_y,canvas.zoom,now()]).map_err(|e|e.to_string())?;Ok(())}
#[tauri::command]fn trash_canvas(id:String,state:State<AppState>)->Result<(),String>{conn(&state)?.execute("UPDATE canvases SET deleted_at=?2 WHERE id=?1",params![id,now()]).map_err(|e|e.to_string())?;Ok(())}
#[tauri::command]fn save_nodes(nodes:Vec<Node>,state:State<AppState>)->Result<(),String>{let mut c=conn(&state)?;let tx=c.transaction().map_err(|e|e.to_string())?;for n in nodes{tx.execute("INSERT INTO nodes(id,canvas_id,asset_id,type,x,y,width,height,rotation,z_index,title,content_json,style_json,created_at,updated_at,deleted_at)VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16) ON CONFLICT(id) DO UPDATE SET canvas_id=excluded.canvas_id,asset_id=excluded.asset_id,type=excluded.type,x=excluded.x,y=excluded.y,width=excluded.width,height=excluded.height,rotation=excluded.rotation,z_index=excluded.z_index,title=excluded.title,content_json=excluded.content_json,style_json=excluded.style_json,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at",params![n.id,n.canvas_id,n.asset_id,n.kind,n.x,n.y,n.width,n.height,n.rotation,n.z_index,n.title,n.content_json,n.style_json,n.created_at,n.updated_at,n.deleted_at]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())}
#[tauri::command]fn trash_nodes(ids:Vec<String>,state:State<AppState>)->Result<(),String>{let mut c=conn(&state)?;let tx=c.transaction().map_err(|e|e.to_string())?;for id in ids{tx.execute("UPDATE nodes SET deleted_at=?2 WHERE id=?1",params![id,now()]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())}
#[tauri::command]fn restore_items(kind:String,ids:Vec<String>,state:State<AppState>)->Result<(),String>{let table=match kind.as_str(){"canvas"=>"canvases","node"=>"nodes","asset"=>"assets",_=>return Err("无效类型".into())};let mut c=conn(&state)?;let tx=c.transaction().map_err(|e|e.to_string())?;for id in ids{tx.execute(&format!("UPDATE {table} SET deleted_at=NULL WHERE id=?1"),[id]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())}
#[tauri::command]fn permanently_delete(kind:String,ids:Vec<String>,state:State<AppState>)->Result<(),String>{let table=match kind.as_str(){"canvas"=>"canvases","node"=>"nodes","asset"=>"assets",_=>return Err("无效类型".into())};let mut c=conn(&state)?;let tx=c.transaction().map_err(|e|e.to_string())?;for id in ids{if kind=="asset"{let count:i64=tx.query_row("SELECT COUNT(*) FROM nodes WHERE asset_id=?1",[&id],|r|r.get(0)).unwrap_or(1);if count>0{continue}}tx.execute(&format!("DELETE FROM {table} WHERE id=?1"),[id]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())}
fn classify(ext:&str)->&'static str{match ext{"png"|"jpg"|"jpeg"|"gif"|"webp"|"avif"|"svg"|"bmp"=>"image","mp4"|"webm"|"mov"|"mkv"|"avi"=>"video","mp3"|"wav"|"flac"|"aac"|"m4a"|"ogg"=>"audio","pdf"=>"pdf","md"|"markdown"=>"markdown","rs"|"js"|"ts"|"tsx"|"jsx"|"vue"|"py"|"java"|"c"|"cpp"|"h"|"hpp"|"cs"|"go"|"php"|"rb"|"swift"|"kt"|"kts"|"html"|"css"|"scss"|"sql"|"sh"|"ps1"|"toml"|"yaml"|"yml"|"json"|"xml"=>"code",_=>"file"}}
fn extract_text(path:&Path,kind:&str,ext:&str)->String{if kind=="pdf"{return pdf_extract::extract_text(path).unwrap_or_default().chars().take(1_000_000).collect()}let textual=matches!(kind,"markdown"|"code")||matches!(ext,"txt"|"log"|"csv"|"ini"|"cfg"|"conf");if textual{fs::read_to_string(path).unwrap_or_default().chars().take(1_000_000).collect()}else{String::new()}}
fn index_existing(root:&Path,c:&Connection){let rows:Vec<(String,String,String,String)>=match c.prepare("SELECT id,storage_name,extension,extracted_text FROM assets WHERE deleted_at IS NULL"){Ok(mut s)=>s.query_map([],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?,r.get(3)?))).map(|it|it.filter_map(Result::ok).collect()).unwrap_or_default(),Err(_)=>return};for(id,storage,ext,current)in rows{let kind=classify(&ext);let text=if current.is_empty(){extract_text(&root.join(storage),kind,&ext)}else{current};let _=c.execute("UPDATE assets SET type=?2,extracted_text=?3 WHERE id=?1",params![id,kind,text]);let _=c.execute("UPDATE nodes SET type=?2 WHERE asset_id=?1 AND type='file'",params![id,kind]);}}
fn import_one(src:&Path,root:&Path,c:&Connection)->Result<ImportResult,String>{if!src.is_file(){return Err(format!("不是文件: {}",src.display()))}let mut f=fs::File::open(src).map_err(|e|e.to_string())?;let mut hasher=Sha256::new();let mut buf=vec![0u8;1024*1024];loop{let n=f.read(&mut buf).map_err(|e|e.to_string())?;if n==0{break}hasher.update(&buf[..n])}let hash=format!("{:x}",hasher.finalize());if let Ok(id)=c.query_row("SELECT id FROM assets WHERE hash=?1",[&hash],|r|r.get::<_,String>(0)){let data=db::load(c,root)?;return Ok(ImportResult{asset:data.assets.into_iter().find(|a|a.id==id).ok_or("资源记录损坏")?,deduplicated:true})}let ext=src.extension().unwrap_or_default().to_string_lossy().to_lowercase();let kind=classify(&ext);let folder=match kind{"image"=>"images","video"=>"videos","audio"=>"audios",_=>"files"};let storage=format!("assets/{folder}/{hash}{}",if ext.is_empty(){String::new()}else{format!(".{ext}")});let temp=root.join("cache/import").join(format!("{}.part",Uuid::new_v4()));let dest=root.join(&storage);fs::copy(src,&temp).map_err(|e|e.to_string())?;fs::rename(&temp,&dest).map_err(|e|{let _=fs::remove_file(&temp);e.to_string()})?;let meta=fs::metadata(&dest).map_err(|e|e.to_string())?;let extracted=extract_text(&dest,kind,&ext);let t=now();let id=Uuid::new_v4().to_string();let name=src.file_name().unwrap_or_default().to_string_lossy().into_owned();let mime=mime_guess::from_path(src).first_or_octet_stream().to_string();if let Err(e)=c.execute("INSERT INTO assets(id,type,original_name,storage_name,extension,mime_type,size,hash,extracted_text,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?10)",params![id,kind,name,storage,ext,mime,meta.len() as i64,hash,extracted,t]){let _=fs::remove_file(dest);return Err(e.to_string())}let data=db::load(c,root)?;Ok(ImportResult{asset:data.assets.into_iter().find(|a|a.id==id).ok_or("资源创建失败")?,deduplicated:false})}
#[tauri::command]async fn import_files(paths:Vec<String>,state:State<'_,AppState>)->Result<Vec<ImportResult>,String>{let root=root(&state)?;tauri::async_runtime::spawn_blocking(move||{let c=db::open(&root)?;paths.iter().map(|p|import_one(Path::new(p),&root,&c)).collect()}).await.map_err(|e|e.to_string())?}
#[tauri::command]fn import_bytes(name:String,mime_type:String,bytes:Vec<u8>,state:State<AppState>)->Result<ImportResult,String>{let root=root(&state)?;let temp=root.join("cache/import").join(&name);fs::write(&temp,bytes).map_err(|e|e.to_string())?;let c=db::open(&root)?;let out=import_one(&temp,&root,&c);let _=fs::remove_file(temp);let _=mime_type;out}
#[tauri::command]fn export_asset(asset_id:String,path:String,state:State<AppState>)->Result<(),String>{let root=root(&state)?;let c=db::open(&root)?;let rel:String=c.query_row("SELECT storage_name FROM assets WHERE id=?1",[asset_id],|r|r.get(0)).map_err(|e|e.to_string())?;fs::copy(root.join(rel),path).map_err(|e|e.to_string())?;Ok(())}
#[tauri::command]fn asset_text(asset_id:String,state:State<AppState>)->Result<String,String>{conn(&state)?.query_row("SELECT extracted_text FROM assets WHERE id=?1",[asset_id],|r|r.get(0)).map_err(|e|e.to_string())}
#[tauri::command]fn open_asset(asset_id:String,state:State<AppState>)->Result<(),String>{let root=root(&state)?;let c=db::open(&root)?;let _rel:String=c.query_row("SELECT storage_name FROM assets WHERE id=?1",[asset_id],|r|r.get(0)).map_err(|e|e.to_string())?;#[cfg(target_os="windows")]{{use std::os::windows::process::CommandExt;std::process::Command::new("cmd").args(["/C","start","",&root.join(_rel).to_string_lossy()]).creation_flags(0x08000000).spawn().map_err(|e|e.to_string())?;}}Ok(())}
#[tauri::command]fn open_url(url:String)->Result<(),String>{if !(url.starts_with("https://")||url.starts_with("http://")){return Err("仅支持 HTTP/HTTPS 链接".into())}#[cfg(target_os="windows")]{{use std::os::windows::process::CommandExt;std::process::Command::new("cmd").args(["/C","start","",&url]).creation_flags(0x08000000).spawn().map_err(|e|e.to_string())?;}}Ok(())}
#[tauri::command]fn save_edges(edges:Vec<Edge>,state:State<AppState>)->Result<(),String>{let mut c=conn(&state)?;let tx=c.transaction().map_err(|e|e.to_string())?;for e in edges{tx.execute("INSERT OR REPLACE INTO edges(id,canvas_id,source_node_id,target_node_id,type,label,style_json,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9)",params![e.id,e.canvas_id,e.source_node_id,e.target_node_id,e.kind,e.label,e.style_json,e.created_at,e.updated_at]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())}
#[tauri::command]fn delete_edges(ids:Vec<String>,state:State<AppState>)->Result<(),String>{let mut c=conn(&state)?;let tx=c.transaction().map_err(|e|e.to_string())?;for id in ids{tx.execute("DELETE FROM edges WHERE id=?1",[id]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())}
#[tauri::command]fn save_groups(groups:Vec<Group>,state:State<AppState>)->Result<(),String>{let mut c=conn(&state)?;let tx=c.transaction().map_err(|e|e.to_string())?;for g in groups{tx.execute("INSERT OR REPLACE INTO groups(id,canvas_id,name,created_at)VALUES(?1,?2,?3,?4)",params![g.id,g.canvas_id,g.name,now()]).map_err(|e|e.to_string())?;tx.execute("DELETE FROM group_nodes WHERE group_id=?1",[&g.id]).map_err(|e|e.to_string())?;for n in g.node_ids{tx.execute("INSERT INTO group_nodes(group_id,node_id)VALUES(?1,?2)",params![g.id,n]).map_err(|e|e.to_string())?;}}tx.commit().map_err(|e|e.to_string())}
#[tauri::command]fn search(query:String,state:State<AppState>)->Result<Vec<SearchResult>,String>{let c=conn(&state)?;let like=format!("%{}%",query);let mut out=vec![];{let mut s=c.prepare("SELECT id,name FROM canvases WHERE deleted_at IS NULL AND name LIKE ?1 LIMIT 30").map_err(|e|e.to_string())?;for r in s.query_map([&like],|r|Ok(SearchResult{kind:"canvas".into(),id:r.get(0)?,canvas_id:None,title:r.get(1)?,subtitle:"画布".into(),x:None,y:None})).map_err(|e|e.to_string())?{if let Ok(v)=r{out.push(v)}}}{let mut s=c.prepare("SELECT DISTINCT n.id,n.canvas_id,n.title,n.type,n.x,n.y FROM nodes n LEFT JOIN assets a ON a.id=n.asset_id WHERE n.deleted_at IS NULL AND (n.title LIKE ?1 OR n.content_json LIKE ?1 OR a.original_name LIKE ?1 OR a.extracted_text LIKE ?1) LIMIT 100").map_err(|e|e.to_string())?;for r in s.query_map([&like],|r|Ok(SearchResult{kind:"node".into(),id:r.get(0)?,canvas_id:Some(r.get(1)?),title:r.get(2)?,subtitle:r.get(3)?,x:Some(r.get(4)?),y:Some(r.get(5)?)})).map_err(|e|e.to_string())?{if let Ok(v)=r{out.push(v)}}}Ok(out)}
pub fn run(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).plugin(tauri_plugin_opener::init()).manage(AppState(Mutex::new(None))).invoke_handler(tauri::generate_handler![create_workspace,open_workspace,close_workspace,mark_clean_shutdown,create_canvas,update_canvas,trash_canvas,save_nodes,trash_nodes,restore_items,permanently_delete,import_files,import_bytes,export_asset,asset_text,open_asset,open_url,save_edges,delete_edges,save_groups,search]).run(tauri::generate_context!()).expect("failed to run Infinite Canvas")}
